require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.colorscheme'
require 'user.hardline'
require 'user.cmp'
require 'user.lsp'
require 'user.telescope'
require 'user.whichkey'
require 'user.project'
require 'user.nvim-window'
require 'user.tabnine'
require 'user.command-completion'
require 'user.caps2ctrl'
require 'user.erd'

-- require 'user.test'